# Base image to pull
FROM ubuntu:14.04

# Installs and update
RUN apt-get update
RUN apt-get install -y wget
RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt install -y build-essential
# Run bash
CMD bash
